name: Build Go Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Tool
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin] # macOS is darwin
        goarch: [amd64, arm64] # Supported architectures

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build Binary
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/dotfiles-${{ matrix.goos }}-${{ matrix.goarch }}
