name: Build Tool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        arch: [amd64, arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Build Binaries
        run: |
          mkdir -p build
          for OS in ${{ matrix.os }}; do
            for ARCH in ${{ matrix.arch }}; do
              OUTPUT="build/dotfiles-${OS}-${ARCH}"
              GOOS=$OS GOARCH=$ARCH go build -o $OUTPUT
              tar -czf "${OUTPUT}.tar.gz" -C build "$(basename $OUTPUT)"
            done
          done

      - name: Archive Build
        run: |
          cd build
          for FILE in *; do
            tar -czf "${FILE}.tar.gz" "$FILE"
          done
